appbaseio/reactivesearch

index.html, website/pages/index.html
When I minified imagery I changed all `assets` paths to `dist` paths. Forgot to check console for bugs. `app.js` wasn't getting loaded. This fixes it.
=> [hotfix] Repair app.js load script

app/sensors/TagCloud.js, app/stories/TagCloud.stories.js, app/stories/index.js
:white_check_mark: Resolves dynamic `size` udate
:white_check_mark: Resolves dynamic `filterLabel` and `showFilter` updates
=> TagCloud dynamic updates

app/actuators/ResultCard.js, app/actuators/ResultList.js, app/actuators/ViewSwitcher.js, app/sensors/CategorySearch.js, app/sensors/DynamicRangeSlider.js, app/sensors/MultiLevelMenu.js, app/sensors/NestedList.js, app/sensors/NestedMultiList.js, app/sensors/RatingsFilter.js, app/sensors/TagCloud.js
- Change prop `componentStyle` to `style`
- Change actuators `style` prop scope to outer container
=> Change prop componentStyle to style, fix scope

app/sensors/CategorySearch.js, app/sensors/DynamicRangeSlider.js, app/sensors/MultiLevelMenu.js, app/sensors/NestedList.js, app/sensors/NestedMultiList.js, app/sensors/RatingsFilter.js, app/sensors/TagCloud.js, app/stories/DynamicRangeSlider.stories.js, app/stories/MultiLevelMenu.stories.js, examples/CategorySearch/app.js, examples/NestedList/app.js, examples/NestedMultiList/app.js, examples/RatingsFilter/app.js, examples/TagCloud/app.js
Should resolve #92 and #94 when merged :v:
=> Fixes for Slider issue and onQueryChange

app/actuators/ResultCard.js, app/actuators/ResultList.js
Fixes [#223](https://github.com/appbaseio/reactivebase/issues/223)
=> fix: ResultList, ResultCard scroll-container height

app/actuators/ResultCard.js, app/actuators/ResultList.js
Should also resolve https://github.com/appbaseio/reactivebase/issues/224
=> Fixes stream update data issue in actuators

app/actuators/ResultCard.js, app/actuators/ResultList.js
=> :bug: Fix delete with stream in ResultList/Card

app/sensors/CategorySearch.js, app/sensors/NestedList.js, app/sensors/NestedMultiList.js, app/sensors/RatingsFilter.js, app/sensors/TagCloud.js
Fixes [#209](https://github.com/appbaseio/reactivebase/issues/209)
=> fix: URLParams behavior

packages/web/src/components/result/ReactiveList.js, packages/web/src/components/result/ResultCard.js, packages/web/src/components/result/ResultList.js
=> Add support for streaming

packages/native/example/src/App.js, packages/native/src/components/result/ReactiveList.js, packages/web/src/components/result/ResultList.js
=> native: ReactiveList - Add streaming support

packages/native/example/storybook/helpers/index.js, packages/native/src/components/list/SingleDropdownList.js, packages/web/src/components/list/MultiDropdownList.js, packages/web/src/components/list/SingleDropdownList.js
=> native: Ignore the bucket key with an empty or whitespace value

packages/native/src/components/date/DatePicker.js, packages/native/src/components/date/DateRange.js
=> native: Date<x> fix reset button bug

packages/web/src/components/list/SingleDropdownList.js, packages/web/src/components/list/SingleList.js
Implementation for #291. I have only implemented the suggested feature for SingleDropdownList and SingleList. I have not yet implemented it for MultiDropdownList and MultiList.
=> web: support filtering by items with missing property in SingleDropdownList and SingleList.

packages/web/src/components/list/MultiDropdownList.js, packages/web/src/components/list/MultiList.js
Implementation for #291.
Resolves #291
=> web: support filtering items with a missing property in MultiDropdownList and MultiList

packages/web/src/components/range/DynamicRangeSlider.js
For issue #284 
Doesn't solve the tooltip part but exposes the value so can at least do what AirBnb does
i.e the rangeLabels update with the slider values
=> Expose prop callback for slider values

packages/web/src/components/basic/DataController.js, packages/web/src/components/basic/NumberBox.js, packages/web/src/components/basic/TagCloud.js, packages/web/src/components/basic/TextField.js, packages/web/src/components/basic/ToggleButton.js, packages/web/src/components/date/DatePicker.js, packages/web/src/components/date/DateRange.js, packages/web/src/components/list/MultiDataList.js, packages/web/src/components/list/MultiDropdownList.js, packages/web/src/components/list/SingleDataList.js, packages/web/src/components/list/SingleDropdownList.js, packages/web/src/components/list/SingleList.js, packages/web/src/components/range/DynamicRangeSlider.js, packages/web/src/components/range/MultiDropdownRange.js, packages/web/src/components/range/MultiRange.js, packages/web/src/components/range/RangeSlider.js, packages/web/src/components/range/RatingsFilter.js, packages/web/src/components/range/SingleDropdownRange.js, packages/web/src/components/range/SingleRange.js, packages/web/src/components/search/CategorySearch.js, packages/web/src/components/search/DataSearch.js
Also, check web: RangeInput
https://github.com/appbaseio/reactivesearch/blob/cfc2db1404bc893e0d90d47140d46f70376e3c9a/packages/web/src/components/range/RangeInput.js#L69-L80
=> web: Fix onValueChange behavior in all components

packages/web/src/components/date/DateRange.js, packages/web/src/styles/DateContainer.js, yarn.lock
=> Date Range Error

packages/web/src/components/basic/ReactiveBase.js
this depends on corresponding  change in [appbase-js](https://github.com/appbaseio/appbase-js)
=> prop on ReactiveBase to provide a beforeSend handler on Appbase

packages/maps/src/components/basic/GeoDistanceDropdown.js, packages/maps/src/components/basic/GeoDistanceSlider.js, yarn.lock
=> added country  restriction props in Geodropdown

packages/web/src/components/search/CategorySearch.js, packages/web/src/components/search/DataSearch.js
=> Fixed cursor jumping in input field [Issue #394]

packages/web/src/components/result/ReactiveList.d.ts, packages/web/src/components/result/ReactiveList.js
=> web: Add support for scrollTarget

packages/web/src/components/basic/URLParamsProvider.js
=> web: Fix SelectedFilters and URLParams behavior - closes #497

packages/web/CHANGELOG.md, packages/web/src/components/basic/ReactiveBase.js
=> web : rename beforeSend to transformRequest in Reactivebase

packages/web/src/components/basic/ReactiveBase.js
=> web : Handle transformRequest initialization in RS

packages/web/src/components/range/RatingsFilter.js
=> Fix: pass showFilter value based on props

packages/web/src/components/list/MultiList.d.ts, packages/web/src/components/list/MultiList.js
=> nested object mapping support for MultiList

packages/vue/src/components/range/MultiRange.jsx, packages/vue/src/index.js
Added Vue Reactive Search Component.
=> Added MultiRange Component

site/demos/producthunt/src/components/Header.js
Turned auto-suggest off for ProductHunt App.
=> turned auto-suggest off

packages/web/package.json
cross-env added to avoid reactiveSearch set up issues in Windows 10.
=> cross-env added

packages/vue/src/components/range/RangeSlider.jsx, packages/vue/src/styles/Slider.js
=> vue: rangeSlider UI Updates

packages/web/src/components/basic/ReactiveComponent.js, packages/web/src/components/basic/TagCloud.d.ts, packages/web/src/components/basic/TagCloud.js, packages/web/src/components/list/MultiDropdownList.d.ts, packages/web/src/components/list/MultiDropdownList.js, packages/web/src/components/list/MultiList.d.ts, packages/web/src/components/list/MultiList.js, packages/web/src/components/list/SingleDropdownList.d.ts, packages/web/src/components/list/SingleDropdownList.js, packages/web/src/components/list/SingleList.d.ts, packages/web/src/components/list/SingleList.js, packages/web/src/components/range/DynamicRangeSlider.d.ts, packages/web/src/components/range/DynamicRangeSlider.js, packages/web/src/components/search/CategorySearch.d.ts, packages/web/src/components/search/CategorySearch.js, packages/web/src/components/search/DataSearch.d.ts, packages/web/src/components/search/DataSearch.js, packages/web/src/styles/Input.js, yarn.lock
This PR has the following fixes.
https://github.com/appbaseio/reactivesearch/issues/227
https://github.com/appbaseio/reactivesearch/issues/250
https://github.com/appbaseio/reactivesearch/issues/584
Features
- Add loader in search components
- Add loader in range components
- Add loader in list & base components
- Provide `isLoading` as a prop in `ReactiveComponent` child
=> web: Add loader support

packages/web/src/styles/FormControlList.js
> ### New Checkbox Styles - 
> ### New Radio Styles -
=> web: Fix Checkbox & Radio Styles

packages/vue/src/components/range/RangeSlider.jsx, packages/vue/src/styles/Slider.js, packages/vue/src/utils/vueTypes.js
=> vue: Add labels in RangeSlider

site/demos/airbeds/src/components/App.js, site/demos/polygon/src/index.js, site/demos/polyline/src/index.js
=> Site: Fix demos credentials

packages/vue/src/components/range/RangeSlider.jsx, packages/vue/src/styles/Slider.js, yarn.lock
Preview: 
Now style matches the default style for ReactiveSearch. Check [here](https://opensource.appbase.io/playground/?selectedKind=Range%20components%2FRangeSlider&selectedStory=Basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs).
=> vue: update Slider Styles & Fix z-index

packages/web/examples/MultiDataList/src/index.js, packages/web/examples/SingleDataList/src/index.js, packages/web/examples/TagCloud/src/index.js, packages/web/examples/ToggleButton/src/index.js, packages/web/examples/ssr/pages/resultlist.js, packages/web/examples/ssr/pages/singledatalist.js, packages/web/examples/ssr/pages/togglebutton.js, packages/web/src/components/list/MultiDataList.d.ts, packages/web/src/components/list/MultiDataList.js, packages/web/src/components/list/SingleDataList.d.ts, packages/web/src/components/list/SingleDataList.js, packages/web/src/components/list/utils.js
- Update examples to use new meetup_app
Resolves #270
=> Add showCount and renderListItem to Single/MultiDataList

site/demos/producthunt/src/App.js, site/demos/producthunt/src/components/Header.js, site/demos/producthunt/src/components/Results.js, site/demos/producthunt/src/components/SearchFilters.js
=> Demos: Fix product hunt cred and mappings

packages/native/example/App.js, packages/web/examples/RatingsFilter/src/index.js, packages/web/examples/ReactiveComponent/src/index.js, site/demos/ecommerce/src/App.js, site/demos/ecommerce/src/components/Header.js, site/demos/ecommerce/src/components/Results.js, site/demos/ecommerce/src/components/SearchFilters.js
=> Site: Fix Car Store Credential & Mappings

packages/maps-native/example/package.json, packages/maps-native/package.json, packages/native/example/package.json, packages/native/example/yarn.lock, packages/native/package.json, packages/web/examples/withStreaming/package.json, packages/web/package.json, yarn.lock
=> Update appbase-js version

packages/vue/examples/range-slider/.eslintignore, packages/vue/examples/range-slider/.gitignore, packages/vue/examples/range-slider/README.md, packages/vue/examples/range-slider/package.json, packages/vue/examples/range-slider/src/App.vue, packages/vue/examples/range-slider/src/main.js, packages/vue/examples/range-slider/src/styles.css
Added example for `RangeSlider` component of vue RS.
=> vue: vueRs RangeSlider example added.

packages/vue/src/styles/FormControlList.js
=> vue: Fix checkbox & radio button styles

packages/vue/examples/multi-Range/.eslintignore, packages/vue/examples/multi-Range/.gitignore, packages/vue/examples/multi-Range/README.md, packages/vue/examples/multi-Range/package.json, packages/vue/examples/multi-Range/src/App.vue, packages/vue/examples/multi-Range/src/main.js, packages/vue/examples/multi-Range/src/styles.css, packages/vue/src/components/list/MultiDropdownList.jsx
1 - Added example for `multiRange`.
2 - VueRs: MultiDropdownList now emits an `array of selected values`, instead of returning a single `selectedvalue`.
=> Multi range example

packages/web/src/server/index.js
Details on this issue: https://github.com/appbaseio/reactivesearch/issues/696
=> feat: add SSR support for transformRequest

packages/web/src/components/basic/DataController.js, packages/web/src/components/basic/NumberBox.js, packages/web/src/components/basic/ReactiveComponent.js, packages/web/src/components/basic/TagCloud.js, packages/web/src/components/basic/TextField.js, packages/web/src/components/basic/ToggleButton.js, packages/web/src/components/date/DatePicker.js, packages/web/src/components/date/DateRange.js, packages/web/src/components/list/MultiDataList.js, packages/web/src/components/list/MultiDropdownList.js, packages/web/src/components/list/MultiList.js, packages/web/src/components/list/SingleDataList.js, packages/web/src/components/list/SingleDropdownList.js, packages/web/src/components/list/SingleList.js, packages/web/src/components/range/DynamicRangeSlider.js, packages/web/src/components/range/MultiDropdownRange.js, packages/web/src/components/range/MultiRange.js, packages/web/src/components/range/RangeSlider.js, packages/web/src/components/range/RatingsFilter.js, packages/web/src/components/range/SingleDropdownRange.js, packages/web/src/components/range/SingleRange.js, packages/web/src/components/result/ReactiveList.js, packages/web/src/components/search/CategorySearch.js, packages/web/src/components/search/DataSearch.js, packages/web/src/utils/index.js, yarn.lock
=> web: Richer support for queryDSL in defaultQuery and customQuery props

packages/web/src/components/list/MultiDataList.js, packages/web/src/components/list/MultiDropdownList.js, packages/web/src/components/list/MultiList.js, packages/web/src/components/list/SingleDataList.js, packages/web/src/components/list/SingleDropdownList.js, packages/web/src/components/list/SingleList.js, packages/web/src/components/shared/Dropdown.js
When there are no `listItems` to be displayed, we can render a message using `onNoResults` prop.
Thoughts? @lakhansamani @bietkul @metagrover
=> web: renderNoResults

packages/vue/src/components/list/MultiDropdownList.jsx
=> vue: Fix defaultSelected values in MultiDropdownList

packages/native/src/components/search/DataSearch.js
- added handleUserSelection method
- invoking handleUserSelection from ListItem.onPress
- invoking original selectSuggestion method from handleUserSelection
=> native: added support for onValueSelected to DataSearch

packages/web/src/components/date/DatePicker.js
=> web: Add nestedField in DatePicker

packages/maps/src/components/basic/GeoDistanceDropdown.js, packages/maps/src/components/basic/GeoDistanceSlider.js
Note: I wasn't having proper data to test maps, the request was successful but the result was not visible because I had nested data on few ids.
=> web: Add nestedField support in Maps

packages/web/src/components/date/DatePicker.js, packages/web/src/components/date/DateRange.js
=> web: Make Date Input Editable
