- app/assets/css/style.css
- app/assets/styles/partials/components/_categorysearch.scss
- app/assets/styles/partials/theme/_default.scss
- app/sensors/CategorySearch.js
- examples/CategorySearch/app.js
- package.json
- yarn.lock
**CategorySearch** now uses `react-autosuggest` instead of `react-select` and supports an `autoSuggest` prop
> Sync CategorySearch with DataSearch for #57

- app/sensors/ToggleList.js
- app/stories/index.js
Earlier we were using `indexOf` which was causing incorrect and weird behavior.
Say a ToggleList has `Social`, `Travel`, `Music`
Then even for `defaultSelected=['Socialsome', 'goTravelgo']` it would select `Social` and `Travel`
Also fixes similar behavior with `multiSelect={false}`
> Fix ToggleList issue to correctly match defaultSelected

- app/actuators/ResultCard.js
- app/actuators/ResultList.js
Support for `onData` prop object - custom `className` property that gets injected with: 
- ResultList: `class="rbc-resultcard-item custom-class"`
- ResultCard: `class="rbc-resultlist-item custom-class"`
Example usage:
```jsx
onData={
function(res) {
return {
image: res.image,
title: res.name,
className: "custom-class",
desc: (
<div>
<div className="price">${res.price}</div>
<p>{res.room_type} · {res.accommodates} guests</p>
</div>
),
url: res.listing_url
}
}
}
```
> feat: onData prop className support

- README.md
Hey there 👋 
Just noticed you have this comparison table here; InstantSearch.js is also available for development without framework (vanilla JS or jQuery): https://community.algolia.com/instantsearch.js/
> add vanilla JS to InstantSearch

- packages/web/src/components/basic/TextField.js
🕸 : TextField pass down [ref prop](https://reactjs.org/docs/refs-and-the-dom.html) as func.
> web: TextField pass down ref prop

- package.json
- yarn.lock
Decrease precommit time drastically by running `eslint` **only over files that are staged**. :rocket:
Can also be configured like this to fix and commit: :100: 
```js
"lint-staged": {
"*.js": [
"eslint --fix",
"git add"
]
},
```
> Optimize precommit time

- packages/web/src/components/search/CategorySearch.d.ts
- packages/web/src/components/search/CategorySearch.js
- packages/web/src/components/search/DataSearch.d.ts
- packages/web/src/components/search/DataSearch.js
Resolves #254 
- introduces a new prop onValueSelected for `DataSearch` and `CategorySearch`
- changes blur behavior, does not auto blur after a selection
has been made
- fixes an issue with stale values in onValueChange when selecting
a suggestion
- fixes an issue with suggestions not displaying sometimes when
clearing characters with backspace
If the changes look good, I can update the docs
> web: Add onValueSelected for search components #254

- packages/web/src/components/result/ReactiveList.js
- yarn.lock
Fix for #371 
- Update ReactiveList `handleSortChange`
- Send the options.from = 0
- setState({ from: 0, currentPage: 0 }) setting the correct page in the state, and force re-render the correct pagination with the first page selected
> Fix issue #371 resetting page number on sort change

- packages/web/src/components/result/ReactiveList.js
When we render a ReactiveList without a parent ResultCard, in those scenarios listClass prop is not passed which lead to this issue
https://github.com/appbaseio/reactivesearch/issues/416
Setting it's default value to empty string fixes that.
> listClass prop defaulted to an empty string value

- packages/web/src/components/basic/SelectedFilters.js
- packages/web/src/components/date/DateRange.js
- packages/web/src/components/result/ReactiveList.js
- Added a new prop onClear to SelectedFilters that will be invoked with the component name and the value of the selected filter being cleared.
- When clearAll is clicked this function will be called with just param and that would be null to indicate that the clearAll has been called.
- DateRange dataField prop should accept both string and array 
This is fix for https://github.com/appbaseio/reactivesearch/issues/401
and
https://github.com/appbaseio/reactivesearch/issues/421
> onClear Prop added to SelectedFilters component and dataField prop should accept both string and array

- packages/web/src/components/basic/ReactiveComponent.js
This checks for changes to `ReactiveComponent`'s `react` prop after the component has mounted in order to update the state accordingly - similar to several of the other web UI components.
> web: check for react prop changes in ReactiveComponent

- packages/web/examples/ssr/pages/index.js
a followup for discussion in #441 
pagination in this example now works even with js disabled, but for now you'll need to modify url manually (i.e. `?SearchResult=1` or `?SearchResult=2`) because pagination component needs some changes to be clickable while js is disabled.
> Get initial search state from query params to make SSR pagination work.

- package.json
- packages/web/src/components/list/MultiList.d.ts
I made the fix as we discussed in https://github.com/appbaseio/reactivesearch/issues/523
I also had to add a few things to the package.json to get things to run. eslint also throws a lot of errors but that might be just CRLF/LF issues on my mac here.
Change is minimal.
> fix to mappings file for multilist

- packages/web/CHANGELOG.md
- packages/web/src/components/basic/NumberBox.js
- packages/web/src/components/basic/TagCloud.js
- packages/web/src/components/basic/ToggleButton.js
- packages/web/src/components/date/DatePicker.js
- packages/web/src/components/date/DateRange.js
- packages/web/src/components/list/MultiDataList.js
- packages/web/src/components/list/MultiDropdownList.js
- packages/web/src/components/list/MultiList.js
- packages/web/src/components/list/SingleDataList.js
- packages/web/src/components/list/SingleDropdownList.js
- packages/web/src/components/list/SingleList.js
- packages/web/src/components/range/DynamicRangeSlider.js
- packages/web/src/components/range/MultiDropdownRange.js
- packages/web/src/components/range/MultiRange.js
- packages/web/src/components/range/RangeSlider.js
- packages/web/src/components/range/RatingsFilter.js
- packages/web/src/components/range/SingleDropdownRange.js
- packages/web/src/components/range/SingleRange.js
- packages/web/src/components/result/ReactiveList.js
- packages/web/src/components/result/ResultCard.js
- packages/web/src/components/result/ResultList.js
- packages/web/src/components/search/CategorySearch.js
- packages/web/src/components/search/DataSearch.js
- ReactiveCore would use these to set the analytics related values
Resolves #484. This PR is necessary for the analytics logic in reactivecore to work. In the next PR I'll include support for filters and click analytics.
[Docs](https://opensource.appbase.io/reactive-manual/advanced/analytics.html)
> web: add analytics support

- packages/web/src/components/list/MultiDropdownList.d.ts
- packages/web/src/components/list/MultiDropdownList.js
- packages/web/src/components/list/MultiList.d.ts
- packages/web/src/components/list/MultiList.js
- packages/web/src/components/list/SingleDropdownList.d.ts
- packages/web/src/components/list/SingleDropdownList.js
- packages/web/src/components/list/SingleList.d.ts
- packages/web/src/components/list/SingleList.js
- packages/web/src/components/list/utils.js
- packages/web/src/components/shared/Dropdown.js
- packages/web/src/styles/Button.js
Adds on demand loading in list components for https://github.com/appbaseio/reactivesearch/issues/515
- Refactor query options for list components
- Add `showLoadMore` and composite aggs in list components (ES >= 6 required)
I spent a lot of time understanding composite aggs (limited resources on internet) and this PR includes the best way I found for supporting it in list components. My implementation is quite good IMO but there might be a bit better way to do things with composite aggs.
[Docs](https://opensource.appbase.io/reactive-manual/list-components/singledropdownlist.html#props)
**NOTE**: Composite aggs are fairly new and in beta. This API is experimental and might need changes if composite aggs changes in the future.
> Add on demand loading for list components

- packages/web/src/components/list/MultiDropdownList.d.ts
- packages/web/src/components/list/MultiDropdownList.js
- packages/web/src/components/list/MultiList.d.ts
- packages/web/src/components/list/MultiList.js
- packages/web/src/components/list/SingleDropdownList.d.ts
- packages/web/src/components/list/SingleDropdownList.js
- packages/web/src/components/list/SingleList.d.ts
- packages/web/src/components/list/SingleList.js
See: https://github.com/appbaseio/reactivesearch/issues/515#issuecomment-425150797
The prop is a `string` to be consistent with `missingLabel`, `filterLabel`, etc. It's called `*Label` for the same reason. Still, I can edit the PR and change behavior.
> loadMoreLabel

- packages/web/src/components/result/ReactiveList.js
Following error occurred, if scrollTarget was not mentioned for `ResultList` or `ReactiveList`
﻿https://www.dropbox.com/s/k47dv2nuacy15bg/Screenshot%202018-10-07%2008.49.30.png?dl=0
> Fix unmounting of ReactiveList without scrollTarget

- packages/web/src/components/search/CategorySearch.d.ts
- packages/web/src/components/search/CategorySearch.js
- packages/web/src/components/search/DataSearch.d.ts
- packages/web/src/components/search/DataSearch.js
This PR is to resolve missing props on `DataSearch` and `CategorySearch` as documented in #591
> add renderSuggestions as props on DataSearch and CategorySearch (#591)

- packages/maps/src/components/basic/GeoDistanceSlider.js
- packages/web/src/components/range/DynamicRangeSlider.js
- packages/web/src/components/range/RangeSlider.js
- packages/web/src/components/range/addons/SliderHandle.js
Close #597 
Custom Content:
```js
<RangeSlider
dataField="ratings_count"
componentId="BookSensor"
range={{
start: 3000,
end: 50000,
}}
rangeLabels={{
start: '3K',
end: '50K',
}}
tooltipTrigger="always"
renderTooltipData={
data => <h5 style={{color: 'papayawhip',textDecoration:'underline'}}>{data}</h5>
}
/>
```
For `toLocaleString`
`data.toLocaleString('ar-EG')`
---
**DEMO**
> web: Add renderTooltipData for custom tooltip content

- packages/vue/src/components/range/RangeSlider.jsx
- packages/vue/src/utils/vueTypes.js
`mergeTooltip={ true }` // merges tooltip
`tooltipTrigger = "none"` // show tooltip in various events
`tooltipTrigger` can have 3 values - `always`, `hover`, `none`.
@divyanshu-rawat Can you please update the docs & Stories for this ?
> vue: Add tooltip props in RangeSlider

- packages/web/src/components/range/RangeInput.js
**Issue**
- While typing value in end input, it doesn't allow the user to enter value less than start value, because `RangeSlider` change handler resets it to start value.
> Remove input validation onChange of slider

- packages/vue/src/components/range/RangeSlider.jsx
Closes #728  #721 
Remove `tooltipTrigger` & `mergeTooltip` as this can be now done with `sliderOptions`
Usage: 
```
:sliderOptions="{
'formatter': function(value){
return '$' + value
},
'tooltip': 'hover'
}"
```
> vue: Add sliderOptions in RangeSlider

- packages/web/src/components/basic/URLParamsProvider.js
Oops. It still fails for #607 (half-fixed via #752) because URLParamsProvider has the same problem.
> web: following #752
